[source.crates-io]
#replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"



[target.mipsel-unknown-linux-gnu]
    linker = "/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-gcc"
    ar = "/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-ar"


[target.mipsel-unknown-linux-uclibc]
    rustflags = [
        "-C", "link-args=-muclibc",
        # "-C", "link-args=-Wl,-no-pie",
        "-C", "link-arg=-msoft-float",
        # "-C", "target-feature=+fp64",
        # "-C", "link-arg=-Wl,-rpath,/system/nfs"
    ]
    #linker = "mipsel-linux-gnu-gcc"
    linker = "/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-uclibc-gnu-gcc"
    ar = "/opt/mips-gcc540-glibc222-64bit-r3.3.0/bin/mips-linux-gnu-ar"
