#[allow(non_upper_case_globals)]
/* automatically generated by rust-bindgen 0.70.1 */

pub const BITS_PER_BYTE: u32 = 8;
pub const ASM_INPUT_G: &[u8; 2] = b"g\0";
pub const ASM_INPUT_RM: &[u8; 3] = b"rm\0";
pub const ___GFP_SKIP_ZERO: u32 = 0;
pub const ___GFP_SKIP_KASAN: u32 = 0;
pub const ___GFP_NOLOCKDEP: u32 = 0;
pub const ___GFP_NO_OBJ_EXT: u32 = 0;
pub const ___GFP_DMA_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_DMA_BIT;
pub const ___GFP_HIGHMEM_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_HIGHMEM_BIT;
pub const ___GFP_DMA32_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_DMA32_BIT;
pub const ___GFP_MOVABLE_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_MOVABLE_BIT;
pub const ___GFP_RECLAIMABLE_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_RECLAIMABLE_BIT;
pub const ___GFP_HIGH_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_HIGH_BIT;
pub const ___GFP_IO_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_IO_BIT;
pub const ___GFP_FS_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_FS_BIT;
pub const ___GFP_ZERO_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_ZERO_BIT;
pub const ___GFP_UNUSED_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_UNUSED_BIT;
pub const ___GFP_DIRECT_RECLAIM_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_DIRECT_RECLAIM_BIT;
pub const ___GFP_KSWAPD_RECLAIM_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_KSWAPD_RECLAIM_BIT;
pub const ___GFP_WRITE_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_WRITE_BIT;
pub const ___GFP_NOWARN_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_NOWARN_BIT;
pub const ___GFP_RETRY_MAYFAIL_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_RETRY_MAYFAIL_BIT;
pub const ___GFP_NOFAIL_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_NOFAIL_BIT;
pub const ___GFP_NORETRY_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_NORETRY_BIT;
pub const ___GFP_MEMALLOC_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_MEMALLOC_BIT;
pub const ___GFP_COMP_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_COMP_BIT;
pub const ___GFP_NOMEMALLOC_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_NOMEMALLOC_BIT;
pub const ___GFP_HARDWALL_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_HARDWALL_BIT;
pub const ___GFP_THISNODE_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_THISNODE_BIT;
pub const ___GFP_ACCOUNT_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_ACCOUNT_BIT;
pub const ___GFP_ZEROTAGS_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_ZEROTAGS_BIT;
pub const ___GFP_LAST_BIT: _bindgen_ty_1 = _bindgen_ty_1::___GFP_LAST_BIT;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum _bindgen_ty_1 {
    ___GFP_DMA_BIT = 0,
    ___GFP_HIGHMEM_BIT = 1,
    ___GFP_DMA32_BIT = 2,
    ___GFP_MOVABLE_BIT = 3,
    ___GFP_RECLAIMABLE_BIT = 4,
    ___GFP_HIGH_BIT = 5,
    ___GFP_IO_BIT = 6,
    ___GFP_FS_BIT = 7,
    ___GFP_ZERO_BIT = 8,
    ___GFP_UNUSED_BIT = 9,
    ___GFP_DIRECT_RECLAIM_BIT = 10,
    ___GFP_KSWAPD_RECLAIM_BIT = 11,
    ___GFP_WRITE_BIT = 12,
    ___GFP_NOWARN_BIT = 13,
    ___GFP_RETRY_MAYFAIL_BIT = 14,
    ___GFP_NOFAIL_BIT = 15,
    ___GFP_NORETRY_BIT = 16,
    ___GFP_MEMALLOC_BIT = 17,
    ___GFP_COMP_BIT = 18,
    ___GFP_NOMEMALLOC_BIT = 19,
    ___GFP_HARDWALL_BIT = 20,
    ___GFP_THISNODE_BIT = 21,
    ___GFP_ACCOUNT_BIT = 22,
    ___GFP_ZEROTAGS_BIT = 23,
    ___GFP_LAST_BIT = 24,
}
pub type gfp_t = libc::c_uint;
pub const RUST_CONST_HELPER_GFP_ATOMIC: gfp_t = 2080;
pub const RUST_CONST_HELPER_GFP_KERNEL: gfp_t = 3264;
pub const RUST_CONST_HELPER_GFP_KERNEL_ACCOUNT: gfp_t = 4197568;
pub const RUST_CONST_HELPER_GFP_NOWAIT: gfp_t = 10240;
pub const RUST_CONST_HELPER___GFP_ZERO: gfp_t = 256;
pub const RUST_CONST_HELPER___GFP_HIGHMEM: gfp_t = 2;
